# Generated by Django 6.0.3 on 2026-04-02 00:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
