name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: medical_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5433:5432

    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install
      